"""Site meta files generated by scripts/build.py: robots.txt, sitemap.xml,
llms.txt, and the in-site API documentation tab. These tests pin the
committed generated files so a build.py change that drops or breaks one
fails loudly until the site is regenerated."""
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE_URL = "https://cheapinfra-resources.wyrdwerk.com"
SM_NS = "{http://www.sitemaps.org/schemas/sitemap/0.9}"


class TestRobots(unittest.TestCase):
    def test_allows_all_and_points_at_sitemap(self):
        robots = (ROOT / "robots.txt").read_text(encoding="utf-8")
        self.assertIn("User-agent: *", robots)
        self.assertIn("Allow: /", robots)
        self.assertIn(f"Sitemap: {SITE_URL}/sitemap.xml", robots)
        # collection is read-only and public; nothing is disallowed
        self.assertNotIn("Disallow:", robots)


class TestSitemap(unittest.TestCase):
    def test_parses_and_covers_the_site(self):
        root = ET.fromstring((ROOT / "sitemap.xml").read_text(encoding="utf-8"))
        self.assertEqual(root.tag, f"{SM_NS}urlset")
        urls = root.findall(f"{SM_NS}url")
        self.assertTrue(urls, "sitemap has no <url> entries")
        locs = [u.findtext(f"{SM_NS}loc") for u in urls]
        self.assertIn(f"{SITE_URL}/", locs)
        for u in urls:
            lastmod = u.findtext(f"{SM_NS}lastmod")
            self.assertRegex(lastmod or "", r"^\d{4}-\d{2}-\d{2}$")


class TestLlmsTxt(unittest.TestCase):
    def test_llmstxt_shape(self):
        text = (ROOT / "llms.txt").read_text(encoding="utf-8")
        lines = text.splitlines()
        # llmstxt.org: H1 name, blockquote summary, then H2 sections of links
        self.assertTrue(lines[0].startswith("# "))
        self.assertTrue(lines[1].startswith("> "))
        for needle in (
            f"{SITE_URL}/api/v1/search",
            f"{SITE_URL}/api/openapi.yaml",
            f"{SITE_URL}/api/v1/facets.json",
            f"{SITE_URL}/sitemap.xml",
            "bad_filter",           # error codes are spelled out
            "open_source",          # params are spelled out
            "Unknown paths under /api/v1/",  # SPA-fallback warning for agents
        ):
            self.assertIn(needle, text)

    def test_every_markdown_link_is_absolute(self):
        text = (ROOT / "llms.txt").read_text(encoding="utf-8")
        for line in text.splitlines():
            if "](" in line:
                start = line.index("(") + 1
                end = line.index(")", start)
                target = line[start:end]
                self.assertTrue(
                    target.startswith(SITE_URL),
                    f"llms.txt link not absolute: {target}")


class TestApiTab(unittest.TestCase):
    def test_index_has_api_tab_wired_up(self):
        html = (ROOT / "index.html").read_text(encoding="utf-8")
        self.assertIn('data-tab="api"', html)          # tab button
        self.assertIn('id="apidocs"', html)             # panel
        self.assertIn("showTab('api')", html)           # JS wiring
        self.assertIn('href="#view=api"', html)         # shareable link
        # the doc content states the real error codes and cache values
        for needle in ("bad_filter", "method_not_allowed", "next_cursor"):
            self.assertIn(needle, html)
        self.assertIn('aria-label="Library, analytics, or API"', html)


if __name__ == "__main__":
    unittest.main()
